apiVersion: apps/v1
kind: Deployment
metadata: 
  name: microservice
  namespace: microservice
spec:
  selector:
    matchLabels:
      app: microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: bbeckerdarosa/microservice:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
